### ISSUE TITLE
local variable 'entry' referenced before assignment: UnboundLocalError

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2timekeeper#10]
No time is importing and this is in the logs

```
local variable 'entry' referenced before assignment: UnboundLocalError
Traceback (most recent call last):
File "/var/task/ical2tk.py", line 291, in lambda_handler
run()
File "/var/task/ical2tk.py", line 261, in run
if entry:
UnboundLocalError: local variable 'entry' referenced before assignment
```

**Comment by ndpete** [comment]
this is resolved by commit 252f5f3e1f3ef00a8b0438a5825bf191c14d9757

**Comment by pauldeden** [comment]
I can't replicate this anymore even when running the lambda itself without any code changes.

I can't see how it would happen either while looking at the code.  The entry variable is setup in the line right preceding the error without any conditional logic so I don't see how it could be not assigned.

Closing the issue for now.

**Comment by pauldeden** [comment]
I hadn't seen @ndpete's fix before commenting.  It looks like he fixed it before I looked at the code!  Well done!
