### ISSUE TITLE
Importing multiple day events I was there full-time instead of eight hours per day

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2timekeeper#13]
This particular event which is a multiple day event lasting over 80 hours if taken literally should be imported every day that it's in only eight hours each day.

See the Screenshots for details
![img_0923](https://user-images.githubusercontent.com/4304479/30594098-b0abec3e-9d01-11e7-8918-f6e4f1adb5c4.PNG)
![img_0922](https://user-images.githubusercontent.com/4304479/30594099-b0b09e32-9d01-11e7-8701-5772ad624c29.PNG)

**Comment by pauldeden** [comment]
Note, this event was also imported as the same 80.5 hours yesterday.

**Comment by ndpete** [comment]
Looks like the existing logic makes the assumption that multiday events will always be all day events. In this case it looks like there are specific start and stop times and as such it is not catching these as all day events. 

I'm working on some basic logic to resolve this until we can handle it more gracefully.

**Comment by pauldeden** [comment]
Thank you
