### ISSUE TITLE
Add a way for public events to not be imported

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2timekeeper#2]
The use case is the following.

I want ical2slackstatus to show that I am in Crazy Friday on Fridays all day and that I'm in Yoga on Tuesdays and Thursdays but I don't want ical2timekeeper to import them into timekeeper.

The current way they don't get imported into timekeeper is by marking them private.  

Perhaps now we can make them public but then add something to the description of the event to say don't import into timekeeper?

**Comment by joshgubler** [comment]
Since rules are evaluated in order, and we take first match, perhaps we need a special target of /dev/null.
