### ISSUE TITLE
module initialization error: while scanning a double-quoted scalar

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2timekeeper#4]
I first saw this happen after I changed the a line in my yml config file to the following.  Nothing has imported on anyone's calendar for Monday or Tuesday this week due to this.

`      - regex: "Crazy Friday \(war room\) :tada:|Get dinner and go to Tabernacle choir rehearsal|yoga|pick up .*|OIT Singers Weekly Get Together|nap|sleep"
        target: /dev/null`

Here is the stacktrace
```
module initialization error: while scanning a double-quoted scalar
in "<byte string>", line 23, column 16:
- regex: "Crazy Friday \(war room\) :tada ... 
^
found unknown escape character '('
in "<byte string>", line 23, column 31:
- regex: "Crazy Friday \(war room\) :tada:|Get dinner an ... 
^
```

**Comment by pauldeden** [comment]
I changed `- regex: "Crazy Friday (war room) :tada:` to `- regex: "Crazy Friday \(war room\) :tada:` after noticing the first regex didn't match the subject.

In running the regex matching code in the python REPL I was able to confirm that adding backslashes did match the summary I wanted it to.

But, in adding it to the yml file I fear I made the whole file invalid.

**Comment by pauldeden** [comment]
We need to do two things, as I see it, to fix this issue.

1. Make sure there is a way to match event subjects with parens in them
2. Make sure errors like mine in one file or line of the file don't keep other calendar entries for the same person or even worse all peoples' time from being imported (like what is currently happening).

**Comment by joshgubler** [comment]
Another workaround would be to split your "|" into multiple rules and use "substring" instead of "regex".

**Comment by pauldeden** [comment]
Good idea
